# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:

#    runs-on: ubuntu-latest
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
      with:
          lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #python -m pip install -r requirements.txt
        python -m pip install --upgrade -r test_requirements.txt
        python -m pip install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=160 --statistics
    - name: Test with pytest
      run: |
        pytest -vv -s
